# Generated by Django 3.0.3 on 2020-02-29 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0002_auto_20200229_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TimeField(max_length=100)),
                ('price', models.TimeField(max_length=100)),
                ('dateofexpire', models.CharField(max_length=100)),
                ('specfic', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('companyname', models.CharField(max_length=100)),
                ('medtype', models.CharField(max_length=100)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
