# Generated by Django 3.0.2 on 2020-03-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_auto_20200301_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='dateofexpire',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='specfic',
        ),
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='net_weight',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='companyname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medtype',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
