# Generated by Django 3.0.8 on 2020-11-14 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_auto_20200517_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='net_weight',
            new_name='t_quantity',
        ),
        migrations.AlterField(
            model_name='booking',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Medicine'),
        ),
    ]
