# Generated by Django 3.0.8 on 2020-11-14 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_auto_20201114_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='half_qty',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Medicine'),
        ),
        migrations.AlterField(
            model_name='count',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Medicine'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Pharmacy'),
        ),
    ]
