# Generated by Django 3.0.8 on 2020-11-15 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0015_auto_20201114_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_qty', models.CharField(max_length=100)),
                ('payment', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('delivery', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Medicine'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Pharmacy'),
        ),
        migrations.DeleteModel(
            name='Count',
        ),
        migrations.AddField(
            model_name='medbook',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Medicine'),
        ),
    ]
